### ISSUE TITLE
Suggestion to add an example slide

### ISSUE THREAD

**Issue by tcgriffith** [malcolmbarrett/kakashi#1]
Hi, malcolm, Did a quick test and love the look&feel of the theme. 

I'd like to suggest adding the source rmd of the two example slides into this repo so that others can learn how to use it.

BTW, the line-height of the list items seems pretty large! My lists floated out the bottom of my slide.

**Comment by malcolmbarrett** [comment]
Thanks, @tcgriffith! I'm going to close this and split into two different issues. I think I'll just add a demo slide deck with links to the source of the others. Re: the list height, that is somewhat intentional. Everything is sized up a bit to make it hard to put too much in one slide, but maybe I'll add a class for a smaller list so one can use `.small-list[]` or something
